import 'package:flutter/material.dart';

const List<String> countries = [
  'Arab Emirates',
  'Argentina',
  'Austria',
  'Australia',
  'Belgium',
  'Bulgaria',
  'Brazil	',
  'Canada',
  'Switzerland',
  'China',
  'Colombia',
  'Cuba',
  'Czechia',
  'Germany',
  'Egypt',
  'France',
  'United Kingdom',
  'Greece',
  'Hong Kong',
  'Hungary',
  'Indonesia',
  'Ireland',
  'Israel',
  'India',
  'Italy',
  'Japan',
  'Korea',
  'Lithuania',
  'Latvia',
  'Morocco',
  'Mexico',
  'Malaysia',
  'Nigeria',
  'Netherlands',
  'Norway',
  'New Zealand',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Serbia ',
  'Russian Federation',
  'Saudi Arabia',
  'Sweden',
  'Singapore',
  'Slovenia',
  'Slovakia',
  'Thailand',
  'Turkey',
  'Taiwan',
  'Ukraine',
  'USA',
  'Venezuela',
  'South Africa',
];
const List<String> catogories = [
  'business',
  'entertainment',
  'general',
  'health',
  'science',
  'sports',
  'technology'
];

OutlineInputBorder outlineInputBorder =
    OutlineInputBorder(borderRadius: BorderRadius.circular(20));
